on:
  push:
    branches: [master]
  pull_request:
name: check

jobs:
  fmt:
    runs-on: ubuntu-latest
    name: stable / fmt
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install Stable
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - name: rust fmt
        run: cargo fmt --check